"""sync_models_with_db

Revision ID: b82e1628d697
Revises: v_token_expiry_001
Create Date: 2026-01-07 09:08:20.789659+00:00

Migration Description:
    TODO: Add a detailed description of what this migration does.

WARNING: Always test migrations in a development environment before production!
"""
import os
import sys
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Add backend directory to path for migration_helpers import
backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

from migration_helpers import (
    safe_add_column, safe_drop_column,
    safe_create_index, safe_drop_index,
    safe_create_table, safe_drop_table,
    safe_create_foreign_key, safe_drop_constraint,
    column_exists, table_exists, index_exists
)

_NOW_SQL = "now()"

# revision identifiers, used by Alembic.
revision: str = 'b82e1628d697'
down_revision: str | Sequence[str] | None = 'v_token_expiry_001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Apply the migration changes.
    
    Use safe_* functions from migration_helpers to prevent errors:
    - safe_add_column(table, column) - Add column if not exists
    - safe_drop_column(table, column_name) - Drop column if exists
    - safe_create_index(name, table, columns) - Create index if not exists
    - safe_drop_index(name, table) - Drop index if exists
    - safe_create_table(name, *columns) - Create table if not exists
    - safe_drop_table(name) - Drop table if exists
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_logs_event_type', table_name='security_logs')
    op.drop_index('ix_security_logs_timestamp', table_name='security_logs')
    op.drop_index('ix_security_logs_user_id', table_name='security_logs')
    op.drop_table('security_logs')
    op.alter_column('auth_audits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('auth_audits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.drop_index('ix_auth_audits_attempt_at', table_name='auth_audits')
    op.drop_index('ix_auth_audits_email', table_name='auth_audits')
    op.drop_index('ix_auth_audits_status', table_name='auth_audits')
    op.drop_index('ix_auth_audits_user_id', table_name='auth_audits')
    op.drop_constraint('auth_audits_user_id_fkey', 'auth_audits', type_='foreignkey')
    op.create_foreign_key(None, 'auth_audits', 'users', ['user_id'], ['id'])
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('password_resets', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('password_resets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('password_resets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_methods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_methods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_analytics', 'total_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_analytics', 'completed_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_analytics', 'todo_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_analytics', 'in_progress_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_analytics', 'productivity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('project_analytics', 'completion_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('project_analytics', 'active_members',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_analytics', 'total_activities',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_analytics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text(_NOW_SQL),
               existing_nullable=False)
    op.alter_column('project_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_milestones', 'is_completed',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('project_milestones', 'progress_percentage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_milestones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tag_associations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tag_associations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_comments', 'is_edited',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('task_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('task_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_dependencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text(_NOW_SQL),
               nullable=False)
    op.alter_column('task_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_time_tracking', 'is_active',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('task_time_tracking', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_time_tracking', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('todo', 'in_progress', 'done', 'in_review', 'cancelled', name='task_status'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='task_priority'),
               nullable=False)
    op.alter_column('tasks', 'type',
               existing_type=postgresql.ENUM('feature', 'bug', 'improvement', 'documentation', 'research', 'other', name='task_type'),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('token_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('token_blacklist', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_favorites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_productivity', 'tasks_created',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_productivity', 'tasks_completed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_productivity', 'tasks_assigned',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_productivity', 'productivity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_productivity', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_productivity', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_settings', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_settings', 'working_hours_start',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('user_settings', 'working_hours_end',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('user_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    
    # Manually fill NULL values before setting NOT NULL
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE users SET is_verified = FALSE WHERE is_verified IS NULL")
    op.execute("UPDATE users SET failed_login_attempts = 0 WHERE failed_login_attempts IS NULL")
    
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('webhook_event_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('webhook_event_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text(_NOW_SQL))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration changes.
    
    Note: Data loss may occur when reverting certain operations.
    Always backup data before running downgrade in production.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_event_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('webhook_event_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_settings', 'working_hours_end',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('user_settings', 'working_hours_start',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user_settings', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_productivity', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_productivity', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_productivity', 'productivity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_productivity', 'tasks_assigned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_productivity', 'tasks_completed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_productivity', 'tasks_created',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_favorites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('user_favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('token_blacklist', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('token_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('tasks', 'type',
               existing_type=postgresql.ENUM('feature', 'bug', 'improvement', 'documentation', 'research', 'other', name='task_type'),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='task_priority'),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('todo', 'in_progress', 'done', 'in_review', 'cancelled', name='task_status'),
               nullable=True)
    op.alter_column('task_time_tracking', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_time_tracking', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_time_tracking', 'is_active',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('task_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-12-03 12:41:07.451037+00'::timestamp with time zone"),
               nullable=True)
    op.alter_column('task_dependencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('task_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_comments', 'is_edited',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('task_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('task_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('project_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tag_associations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_tag_associations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_milestones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_milestones', 'progress_percentage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_milestones', 'is_completed',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('project_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_analytics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('project_analytics', 'total_activities',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_analytics', 'active_members',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_analytics', 'completion_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('project_analytics', 'productivity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('project_analytics', 'in_progress_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_analytics', 'todo_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_analytics', 'completed_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_analytics', 'total_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_methods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_methods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('payment_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('password_resets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('password_resets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('password_resets', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.drop_constraint(None, 'auth_audits', type_='foreignkey')
    op.create_foreign_key('auth_audits_user_id_fkey', 'auth_audits', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_auth_audits_user_id', 'auth_audits', ['user_id'], unique=False)
    op.create_index('ix_auth_audits_status', 'auth_audits', ['status'], unique=False)
    op.create_index('ix_auth_audits_email', 'auth_audits', ['email'], unique=False)
    op.create_index('ix_auth_audits_attempt_at', 'auth_audits', ['attempt_at'], unique=False)
    op.alter_column('auth_audits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.alter_column('auth_audits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text(_NOW_SQL))
    op.create_table('security_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(_NOW_SQL), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_logs_pkey')
    )
    op.create_index('ix_security_logs_user_id', 'security_logs', ['user_id'], unique=False)
    op.create_index('ix_security_logs_timestamp', 'security_logs', ['timestamp'], unique=False)
    op.create_index('ix_security_logs_event_type', 'security_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###
