"""Initial Check

Revision ID: 58e012fdb79c
Revises:
Create Date: 2025-12-08 02:55:00.450156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e012fdb79c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)

    # Get existing indexes for relevant tables to avoid duplicates
    members_indexes = [i['name'] for i in inspector.get_indexes('project_members')]
    history_indexes = [i['name'] for i in inspector.get_indexes('task_history')]
    tasks_indexes = [i['name'] for i in inspector.get_indexes('tasks')]

    if 'ix_project_members_project_user' not in members_indexes:
        op.create_index('ix_project_members_project_user', 'project_members', ['project_id', 'user_id'], unique=False)

    if 'ix_task_history_project_timestamp' not in history_indexes:
        op.create_index('ix_task_history_project_timestamp', 'task_history', ['project_id', 'timestamp'], unique=False)

    if 'ix_tasks_due_date' not in tasks_indexes:
        op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)

    if 'ix_tasks_project_status' not in tasks_indexes:
        op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index('ix_task_history_project_timestamp', table_name='task_history')
    op.drop_index('ix_project_members_project_user', table_name='project_members')
    # ### end Alembic commands ###
