"""Initial Check

Revision ID: 58e012fdb79c
Revises: 
Create Date: 2025-12-08 02:55:00.450156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e012fdb79c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_members_project_user', 'project_members', ['project_id', 'user_id'], unique=False)
    op.create_index('ix_task_history_project_timestamp', 'task_history', ['project_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index('ix_task_history_project_timestamp', table_name='task_history')
    op.drop_index('ix_project_members_project_user', table_name='project_members')
    # ### end Alembic commands ###
