"""Initial Check

Revision ID: 58e012fdb79c
Revises:
Create Date: 2025-12-08 02:55:00.450156

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58e012fdb79c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The original migration queried the live inspector, which breaks offline
    # SQL generation. PostgreSQL's IF NOT EXISTS keeps upgrades idempotent.
    op.create_index(
        "ix_project_members_project_user",
        "project_members",
        ["project_id", "user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_task_history_project_timestamp",
        "task_history",
        ["project_id", "timestamp"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index("ix_tasks_due_date", "tasks", ["due_date"], unique=False, if_not_exists=True)
    op.create_index(
        "ix_tasks_project_status",
        "tasks",
        ["project_id", "status"],
        unique=False,
        if_not_exists=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_project_status", table_name="tasks", if_exists=True)
    op.drop_index("ix_tasks_due_date", table_name="tasks", if_exists=True)
    op.drop_index("ix_task_history_project_timestamp", table_name="task_history", if_exists=True)
    op.drop_index("ix_project_members_project_user", table_name="project_members", if_exists=True)
