"""add_task_sorting_indexes

Revision ID: 9cd1cf9585b5
Revises: add_user_favorites_001
Create Date: 2025-12-29 23:51:16.945991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd1cf9585b5'
down_revision: Union[str, None] = 'add_user_favorites_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_assignee_updated_at', 'tasks', ['assignee_id', 'updated_at'], unique=False)
    op.create_index('ix_tasks_project_updated_at', 'tasks', ['project_id', 'updated_at'], unique=False)
    # Also adding payment history index here since we couldn't generate it separately
    op.create_index('ix_payment_history_user_created_at', 'payment_history', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_user_created_at', table_name='payment_history')
    op.drop_index('ix_tasks_project_updated_at', table_name='tasks')
    op.drop_index('ix_tasks_assignee_updated_at', table_name='tasks')
    # ### end Alembic commands ###
