"""add_auth_security_features

Revision ID: f7a6e8c1c8b8
Revises: add_refunded_amount
Create Date: 2025-12-27 23:39:36.450510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7a6e8c1c8b8'
down_revision: Union[str, None] = 'add_refunded_amount'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event_logs',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_logs_event_type'), 'webhook_event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_event_logs_stripe_event_id'), 'webhook_event_logs', ['stripe_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_event_logs_user_id'), 'webhook_event_logs', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('uq_project_members_project_user', 'project_members', ['project_id', 'user_id'])
    op.drop_constraint('subscriptions_user_id_key', 'subscriptions', type_='unique')
    op.create_index('ix_tasks_project_due_date', 'tasks', ['project_id', 'due_date'], unique=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('users_github_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('backup_codes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_unique_constraint('users_github_id_key', 'users', ['github_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_index('ix_tasks_project_due_date', table_name='tasks')
    op.create_unique_constraint('subscriptions_user_id_key', 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_project_members_project_user', 'project_members', type_='unique')
    op.alter_column('project_members', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_webhook_event_logs_user_id'), table_name='webhook_event_logs')
    op.drop_index(op.f('ix_webhook_event_logs_stripe_event_id'), table_name='webhook_event_logs')
    op.drop_index(op.f('ix_webhook_event_logs_event_type'), table_name='webhook_event_logs')
    op.drop_table('webhook_event_logs')
    # ### end Alembic commands ###
